<a href="https://colab.research.google.com/github/BoboSamson/BoboSamson/blob/Samson/Pytorch_lab1_Samson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Create a random tensor of shape (7, 7)
import random
import torch

# # Set the random seed

torch.manual_seed(seed=44)
random_tensor = torch.rand(7, 7)


print(f"random tensor of shape (7,7) is \n")
print(f"{random_tensor}")




random tensor of shape (7,7) is 

tensor([[0.7196, 0.7307, 0.8278, 0.1343, 0.6280, 0.7297, 0.2882],
        [0.2112, 0.9836, 0.8722, 0.9650, 0.7837, 0.8076, 0.0608],
        [0.7226, 0.3354, 0.5350, 0.7117, 0.7979, 0.2785, 0.8947],
        [0.6694, 0.8950, 0.4479, 0.4788, 0.3541, 0.0467, 0.7471],
        [0.7821, 0.4296, 0.1128, 0.8413, 0.4978, 0.3593, 0.7470],
        [0.0869, 0.4811, 0.4923, 0.7392, 0.3945, 0.0290, 0.7696],
        [0.6214, 0.0891, 0.4282, 0.0289, 0.7090, 0.3982, 0.1633]])


In [3]:
random_tensor.shape

torch.Size([7, 7])

In [4]:
# Creat random tensor of shape (1, 7)
## Set the seed
torch.manual_seed(seed=44)
random_tensor1 = torch.rand(1, 7)

print(f" random tensor of shape (1, 7) is \n")
print(f"{random_tensor1}\n\n")
random_tensor1.shape


 random tensor of shape (1, 7) is 

tensor([[0.7196, 0.7307, 0.8278, 0.1343, 0.6280, 0.7297, 0.2882]])




torch.Size([1, 7])

In [5]:
print(f"random_tensor shape is {random_tensor.shape} and random_tensor1 shape is {random_tensor1.shape}")

random_tensor shape is torch.Size([7, 7]) and random_tensor1 shape is torch.Size([1, 7])


In [6]:
print(f" The transpose of random_tensor1 is \n")
print(f"{random_tensor1.T}")

 The transpose of random_tensor1 is 

tensor([[0.7196],
        [0.7307],
        [0.8278],
        [0.1343],
        [0.6280],
        [0.7297],
        [0.2882]])


In [7]:
#Matrix multiplication of random_tensor and random_tensor1

print(f" The matrix multiplication of random_tensor * random_tensor1 is \n")
print(f"{random_tensor * random_tensor1.T}")

 The matrix multiplication of random_tensor * random_tensor1 is 

tensor([[0.5178, 0.5258, 0.5957, 0.0967, 0.4519, 0.5251, 0.2074],
        [0.1543, 0.7187, 0.6373, 0.7051, 0.5726, 0.5901, 0.0444],
        [0.5982, 0.2777, 0.4429, 0.5891, 0.6605, 0.2305, 0.7406],
        [0.0899, 0.1202, 0.0602, 0.0643, 0.0476, 0.0063, 0.1004],
        [0.4911, 0.2698, 0.0709, 0.5283, 0.3126, 0.2256, 0.4691],
        [0.0634, 0.3511, 0.3593, 0.5394, 0.2879, 0.0212, 0.5616],
        [0.1791, 0.0257, 0.1234, 0.0083, 0.2043, 0.1148, 0.0471]])


In [8]:
#The  seed  set to 0 for exercise 2 and 3 has the following results

#Create a random tensor of shape (7, 7)
import random

# # Set the random seed

torch.manual_seed(seed=0)
random_tensor = torch.rand(7, 7)


print(f"random tensor of shape (7,7) with seed 0 is \n")
print(f"{random_tensor}")




random tensor of shape (7,7) with seed 0 is 

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


In [9]:
# Creat random tensor of shape (1, 7)
## Set the seed to 0
torch.manual_seed(seed=0)
random_tensor1 = torch.rand(1, 7)

print(f" random tensor of shape (1, 7) with seed 0 is \n")
print(f"{random_tensor1}\n\n")
random_tensor1.shape


 random tensor of shape (1, 7) with seed 0 is 

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])




torch.Size([1, 7])

In [10]:
print(f" The transpose of random_tensor1 with seed 0 is \n")
print(f"{random_tensor1.T}")

 The transpose of random_tensor1 with seed 0 is 

tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])


In [11]:
#Matrix multiplication of random_tensor and random_tensor1 with seed 0

print(f" The matrix multiplication of random_tensor * random_tensor1 with seed 0  is \n")
print(f"{random_tensor * random_tensor1.T}")

 The matrix multiplication of random_tensor * random_tensor1 with seed 0  is 

tensor([[0.2463, 0.3812, 0.0439, 0.0655, 0.1526, 0.3147, 0.2432],
        [0.6887, 0.3500, 0.4858, 0.2680, 0.3086, 0.0172, 0.1297],
        [0.0260, 0.0459, 0.0617, 0.0708, 0.0142, 0.0250, 0.0603],
        [0.1208, 0.0524, 0.1154, 0.0554, 0.0730, 0.1258, 0.0048],
        [0.0569, 0.1148, 0.0938, 0.2865, 0.0541, 0.0830, 0.0463],
        [0.0201, 0.1320, 0.5896, 0.4585, 0.4707, 0.3337, 0.1545],
        [0.2865, 0.0162, 0.0680, 0.1187, 0.3997, 0.3887, 0.1364]])


In [12]:
# Check for GPU
torch.cuda.is_available()

True

In [13]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [14]:
# Check for Apple Silicon GPU
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

False

In [15]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [16]:
seed = 1234

In [17]:
#Create two  random tensors of shape (2, 3) and send both to GPU

torch.manual_seed(seed=1234)
random_tensorA = torch.rand(2, 3)

print(f" random tensor of shape (2, 3)  is \n")
print(f"{random_tensorA}\n\n")
random_tensorA.shape
# Tensor not on GPU
print(f"random_tensorA, random_tensorA.device\n")

# Move tensor to GPU (if available)
tensorA_on_gpu = random_tensorA.to(device)
tensorA_on_gpu



 random tensor of shape (2, 3)  is 

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])


random_tensorA, random_tensorA.device



tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [18]:
#Create two  random tensors of shape (2, 3) and send both to GPU
torch.manual_seed(seed=1234)
random_tensorB = torch.rand(2, 3)

print(f" random tensor of shape (2, 3) is \n")
print(f"{random_tensorB}\n\n")
random_tensorB.shape
# Tensor not on GPU
print(f"random_tensorB, random_tensorB.device\n")

# Move tensor to GPU (if available)
tensorB_on_gpu = random_tensorB.to(device)
tensorB_on_gpu



 random tensor of shape (2, 3) is 

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])


random_tensorB, random_tensorB.device



tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [19]:
#Matrix multiplication of tensorA_on_gpu * tensorB_on _gpu

print(f"The Transpose of tensorB_on_gpu is \n")
print(f"{tensorB_on_gpu.T}")

The Transpose of tensorB_on_gpu is 

tensor([[0.0290, 0.3666],
        [0.4019, 0.0583],
        [0.2598, 0.7006]], device='cuda:0')


In [20]:
print(f"The result of multiplying tensorA_on_gpu * tansorB_on_gpu is\n ")

output = torch.matmul(tensorA_on_gpu, tensorB_on_gpu.T)

print(output)

The result of multiplying tensorA_on_gpu * tansorB_on_gpu is
 
tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')


In [21]:
#Find the maximum and minimum values of the output of matrix multiplication above
print(f"Minimum: {output.min()}\n")
print(f"Maximum: {output.max()}")



Minimum: 0.21611443161964417

Maximum: 0.628727912902832


In [22]:
#Find the maximum and minimum index values of output in 7
# Returns index of max and min values
print(f"Index where max value occurs: {output.argmax()}\n")
print(f"Index where min value occurs: {output.argmin()}")

Index where max value occurs: 3

Index where min value occurs: 1


In [23]:
#Create a random tensor with shape (1, 1, 1, 10)
torch.manual_seed(seed=7)
tensor_C = torch.rand(1, 1, 1, 10)

print(f" random tensor of shape (1, 1, 1, 10) with seed 7 is \n")
print(f"{tensor_C}\n\n")

print(f"{tensor_C.shape}\n")
# Tensor not on GPU
print(tensor_C, tensor_C.device)

# Move tensor to GPU (if available)
tensorC_on_gpu = tensor_C.to(device)


 random tensor of shape (1, 1, 1, 10) with seed 7 is 

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])


torch.Size([1, 1, 1, 10])

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) cpu


In [24]:
#Create a random tensor with shape (1, 1, 1, 10)

tensor_D = tensorC_on_gpu.squeeze()

print(f" tensor_D is \n")
print(f"{tensorC_on_gpu.squeeze()}\n")
print(f"{tensor_D.shape}\n")
# Tensor not on GPU
print(tensor_D, tensor_D.device)

# Move tensor to GPU (if available)
tensorD_on_gpu = tensor_D.to(device)


 tensor_D is 

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513], device='cuda:0')

torch.Size([10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513], device='cuda:0') cuda:0
